/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const TradeRequestMessage = IDL.Record({
  'requester' : IDL.Principal,
  'summary' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Float64,
  'requestType' : IDL.Text,
});
export const ReceiptMessage = IDL.Record({
  'fee' : IDL.Float64,
  'sender' : IDL.Principal,
  'summary' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Float64,
  'receiver' : IDL.Principal,
});
export const MessageType = IDL.Variant({
  'media' : ExternalBlob,
  'tradeRequest' : TradeRequestMessage,
  'receipt' : ReceiptMessage,
  'video' : ExternalBlob,
  'voice' : ExternalBlob,
  'rose' : IDL.Float64,
  'text' : IDL.Text,
  'image' : ExternalBlob,
  'forwardedPost' : IDL.Record({
    'author' : IDL.Principal,
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
    'contentSnippet' : IDL.Text,
    'postId' : IDL.Text,
  }),
});
export const EmailPreferences = IDL.Record({
  'postGift' : IDL.Bool,
  'groupMessage' : IDL.Bool,
  'roseReceipt' : IDL.Bool,
  'tradeRequest' : IDL.Bool,
  'systemNotice' : IDL.Bool,
  'storyView' : IDL.Bool,
  'like' : IDL.Bool,
  'comment' : IDL.Bool,
  'groupAdd' : IDL.Bool,
  'message' : IDL.Bool,
  'roseGift' : IDL.Bool,
  'follow' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'country' : IDL.Text,
  'username' : IDL.Text,
  'birthYear' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'emailPreferences' : IDL.Opt(EmailPreferences),
  'gender' : IDL.Opt(IDL.Text),
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const GroupMessage = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'content' : MessageType,
  'senderProfile' : IDL.Opt(UserProfile),
  'sender' : IDL.Principal,
  'groupId' : IDL.Nat,
  'isEdited' : IDL.Bool,
  'timestamp' : Time,
  'replyToId' : IDL.Opt(IDL.Nat),
  'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Principal))),
  'readBy' : IDL.Vec(IDL.Principal),
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'content' : MessageType,
  'senderProfile' : IDL.Opt(UserProfile),
  'sender' : IDL.Principal,
  'isEdited' : IDL.Bool,
  'timestamp' : Time,
  'replyToId' : IDL.Opt(IDL.Nat),
  'receiver' : IDL.Principal,
  'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Principal))),
  'readBy' : IDL.Vec(IDL.Principal),
});
export const ProfileFilter = IDL.Record({
  'country' : IDL.Opt(IDL.Text),
  'minAge' : IDL.Opt(IDL.Nat),
  'gender' : IDL.Opt(IDL.Text),
  'maxAge' : IDL.Opt(IDL.Nat),
  'minBalance' : IDL.Opt(IDL.Float64),
});
export const ProfileWithPrincipal = IDL.Record({
  'principal' : IDL.Principal,
  'balance' : IDL.Float64,
  'profile' : UserProfile,
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'content' : MessageType,
  'expiresAt' : Time,
  'author' : IDL.Principal,
  'viewCount' : IDL.Nat,
  'viewedBy' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
  'caption' : IDL.Opt(IDL.Text),
  'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Principal))),
});
export const BlockRecord = IDL.Record({
  'blocked' : IDL.Principal,
  'blocker' : IDL.Principal,
  'timestamp' : Time,
});
export const RoseTransactionType = IDL.Variant({
  'buy' : IDL.Null,
  'fee' : IDL.Null,
  'gift' : IDL.Null,
  'mint' : IDL.Null,
  'sell' : IDL.Null,
  'transfer' : IDL.Null,
});
export const RoseTransaction = IDL.Record({
  'id' : IDL.Nat,
  'feeDistributed' : IDL.Float64,
  'transactionType' : RoseTransactionType,
  'sender' : IDL.Opt(IDL.Principal),
  'timestamp' : Time,
  'amount' : IDL.Float64,
  'receiver' : IDL.Opt(IDL.Principal),
});
export const AnalyticsSummary = IDL.Record({
  'activeUsers' : IDL.Nat,
  'totalPlatformFees' : IDL.Float64,
  'totalRosesCirculating' : IDL.Float64,
  'totalRoseTransactions' : IDL.Nat,
  'totalMessages' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRoseGifts' : IDL.Float64,
  'totalPosts' : IDL.Nat,
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'embed' : IDL.Opt(IDL.Text),
  'author' : IDL.Principal,
  'viewCount' : IDL.Nat,
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
});
export const UserAnalytics = IDL.Record({
  'giftsReceived' : IDL.Nat,
  'postCount' : IDL.Nat,
  'roseBalance' : IDL.Float64,
  'reactionsReceived' : IDL.Nat,
  'messageCount' : IDL.Nat,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'participants' : IDL.Vec(IDL.Principal),
  'messages' : IDL.Vec(Message),
  'otherParticipantProfile' : IDL.Opt(UserProfile),
});
export const GroupChat = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'participants' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : Time,
  'admins' : IDL.Vec(IDL.Principal),
  'avatar' : IDL.Opt(ExternalBlob),
});
export const NotificationCount = IDL.Record({
  'groupAddCount' : IDL.Nat,
  'storyViewCount' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'roseGiftCount' : IDL.Nat,
  'systemCount' : IDL.Nat,
  'totalCount' : IDL.Nat,
  'followCount' : IDL.Nat,
  'unreadCount' : IDL.Nat,
  'messageCount' : IDL.Nat,
  'roseReceiptCount' : IDL.Nat,
  'commentCount' : IDL.Nat,
  'tradeRequestCount' : IDL.Nat,
  'postGiftCount' : IDL.Nat,
  'groupMessageCount' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'postGift' : IDL.Null,
  'groupMessage' : IDL.Null,
  'roseReceipt' : IDL.Null,
  'tradeRequest' : IDL.Null,
  'systemNotice' : IDL.Null,
  'storyView' : IDL.Null,
  'like' : IDL.Null,
  'comment' : IDL.Null,
  'groupAdd' : IDL.Null,
  'message' : IDL.Null,
  'roseGift' : IDL.Null,
  'follow' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'linkedId' : IDL.Opt(IDL.Text),
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'notificationType' : NotificationType,
  'isRead' : IDL.Bool,
  'timestamp' : Time,
  'linkedType' : IDL.Opt(IDL.Text),
});
export const PlatformStats = IDL.Record({
  'totalMessages' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalInteractions' : IDL.Nat,
  'totalPosts' : IDL.Nat,
});
export const CommentInteraction = IDL.Record({
  'id' : IDL.Nat,
  'parentCommentId' : IDL.Opt(IDL.Nat),
  'user' : IDL.Principal,
  'comment' : IDL.Text,
  'timestamp' : Time,
  'postId' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const GroupUnreadCount = IDL.Record({
  'groupId' : IDL.Nat,
  'unreadCount' : IDL.Nat,
});
export const DirectUnreadCount = IDL.Record({
  'conversationId' : IDL.Nat,
  'unreadCount' : IDL.Nat,
});
export const UnreadCounts = IDL.Record({
  'groups' : IDL.Vec(GroupUnreadCount),
  'direct' : IDL.Vec(DirectUnreadCount),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const SearchResult = IDL.Variant({
  'postResult' : IDL.Record({
    'author' : IDL.Principal,
    'searchType' : IDL.Text,
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
    'contentSnippet' : IDL.Text,
    'postId' : IDL.Text,
  }),
  'messageResult' : IDL.Record({
    'messageId' : IDL.Nat,
    'senderProfile' : IDL.Opt(UserProfile),
    'sender' : IDL.Principal,
    'searchType' : IDL.Text,
    'conversationId' : IDL.Nat,
    'timestamp' : Time,
    'contentSnippet' : IDL.Text,
    'receiver' : IDL.Principal,
  }),
  'userResult' : IDL.Record({
    'principal' : IDL.Principal,
    'balance' : IDL.Float64,
    'searchType' : IDL.Text,
    'profile' : UserProfile,
  }),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addGroupParticipant' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'buyRosesFromUser' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
  'claimAllRoses' : IDL.Func([], [], []),
  'cleanupExpiredStories' : IDL.Func([], [IDL.Nat], []),
  'clearAllNotifications' : IDL.Func([], [], []),
  'commentOnPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)], [], []),
  'convertBalanceToUsd' : IDL.Func([IDL.Float64], [IDL.Float64], []),
  'convertBalanceToUsdQuery' : IDL.Func(
      [IDL.Float64],
      [IDL.Float64],
      ['query'],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createGroupChat' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Principal), IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'createStory' : IDL.Func([MessageType, IDL.Opt(IDL.Text)], [IDL.Nat], []),
  'deleteCallerProfile' : IDL.Func([], [], []),
  'deleteComment' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteGroupMessage' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteMessage' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteNotification' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'editGroupMessage' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : GroupMessage, 'err' : IDL.Text })],
      [],
    ),
  'editMessage' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
      [],
    ),
  'editPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'filterProfiles' : IDL.Func(
      [ProfileFilter],
      [IDL.Vec(ProfileWithPrincipal)],
      ['query'],
    ),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'forwardGroupMessageToConversation' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
      [],
    ),
  'forwardMessage' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
      [],
    ),
  'forwardMessageToGroup' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : GroupMessage, 'err' : IDL.Text })],
      [],
    ),
  'forwardPostToConversation' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getAllBlockRecords' : IDL.Func([], [IDL.Vec(BlockRecord)], ['query']),
  'getAllRoseTransactions' : IDL.Func(
      [],
      [IDL.Vec(RoseTransaction)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerEmailPreferences' : IDL.Func(
      [],
      [
        IDL.Record({
          'email' : IDL.Opt(IDL.Text),
          'preferences' : IDL.Opt(EmailPreferences),
        }),
      ],
      ['query'],
    ),
  'getCallerPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserAnalytics' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : UserAnalytics, 'err' : IDL.Text })],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getGroupChats' : IDL.Func([], [IDL.Vec(GroupChat)], ['query']),
  'getGroupDetails' : IDL.Func([IDL.Nat], [GroupChat], ['query']),
  'getGroupMessages' : IDL.Func([IDL.Nat], [IDL.Vec(GroupMessage)], ['query']),
  'getGroupTypingUsers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getIcpUsdExchangeRate' : IDL.Func([], [IDL.Float64], []),
  'getNotificationCountByType' : IDL.Func([], [NotificationCount], ['query']),
  'getNotifications' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'notifications' : IDL.Vec(Notification),
        }),
      ],
      ['query'],
    ),
  'getOnlineUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getPinnedConversationMessage' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Message)],
      ['query'],
    ),
  'getPinnedGroupMessage' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(GroupMessage)],
      ['query'],
    ),
  'getPinnedStories' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
  'getPinnedTrendingPost' : IDL.Func([], [IDL.Opt(Post)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getPostComments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CommentInteraction)],
      ['query'],
    ),
  'getPostInteractions' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'totalRosesGifted' : IDL.Float64,
          'forwards' : IDL.Nat,
          'likes' : IDL.Nat,
          'saves' : IDL.Nat,
          'comments' : IDL.Nat,
          'roseGifts' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getPostViewCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPostsFromFollowedUsers' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getRoseBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getRoseSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalCirculating' : IDL.Float64,
          'feeRewards' : IDL.Float64,
          'userBalance' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getRoseTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(RoseTransaction)],
      ['query'],
    ),
  'getSavedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getStoryReactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Principal)))],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTotalCirculatingRoses' : IDL.Func([], [IDL.Float64], ['query']),
  'getTypingUsers' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
  'getUnreadCounts' : IDL.Func([], [UnreadCounts], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Record({ 'profileId' : IDL.Principal })],
      [UserProfile],
      ['query'],
    ),
  'getUserRoseBalance' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
  'getUserStories' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
  'giftRoses' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
  'giftRosesOnPost' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'giftRosesOnStory' : IDL.Func(
      [IDL.Nat, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isOnline' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'leaveConversation' : IDL.Func([IDL.Nat], [], []),
  'leaveGroup' : IDL.Func([IDL.Nat], [], []),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'markAllNotificationsAsRead' : IDL.Func([], [], []),
  'markConversationRead' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markGroupChatRead' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markGroupMessageRead' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markMessageRead' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'markStoryAsViewed' : IDL.Func([IDL.Nat], [], []),
  'pinConversationMessage' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'pinGroupMessage' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'pinPostToTrending' : IDL.Func([IDL.Text], [], []),
  'pinStory' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'reactToGroupMessage' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'reactToMessage' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'reactToStory' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'recordPostView' : IDL.Func([IDL.Text], [], []),
  'removeGroupParticipant' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'requestBuyRoses' : IDL.Func([IDL.Float64], [IDL.Text], []),
  'requestSellRoses' : IDL.Func([IDL.Float64], [IDL.Text], []),
  'saveCallerEmailPreferences' : IDL.Func(
      [IDL.Opt(IDL.Text), EmailPreferences],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePost' : IDL.Func([IDL.Text], [], []),
  'sellRosesToUser' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
  'sendGroupMessage' : IDL.Func(
      [IDL.Nat, MessageType, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Principal, MessageType, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'setGroupTyping' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setTyping' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'universalSearch' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Vec(SearchResult)],
      ['query'],
    ),
  'unlikePost' : IDL.Func([IDL.Text], [], []),
  'unpinConversationMessage' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unpinGroupMessage' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unpinStory' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unpinTrendingPost' : IDL.Func([], [], []),
  'unreactToStory' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unsavePost' : IDL.Func([IDL.Text], [], []),
  'updateGroupAvatar' : IDL.Func([IDL.Nat, IDL.Opt(ExternalBlob)], [], []),
  'updateGroupName' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateLastActive' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const TradeRequestMessage = IDL.Record({
    'requester' : IDL.Principal,
    'summary' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Float64,
    'requestType' : IDL.Text,
  });
  const ReceiptMessage = IDL.Record({
    'fee' : IDL.Float64,
    'sender' : IDL.Principal,
    'summary' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Float64,
    'receiver' : IDL.Principal,
  });
  const MessageType = IDL.Variant({
    'media' : ExternalBlob,
    'tradeRequest' : TradeRequestMessage,
    'receipt' : ReceiptMessage,
    'video' : ExternalBlob,
    'voice' : ExternalBlob,
    'rose' : IDL.Float64,
    'text' : IDL.Text,
    'image' : ExternalBlob,
    'forwardedPost' : IDL.Record({
      'author' : IDL.Principal,
      'timestamp' : Time,
      'image' : IDL.Opt(ExternalBlob),
      'contentSnippet' : IDL.Text,
      'postId' : IDL.Text,
    }),
  });
  const EmailPreferences = IDL.Record({
    'postGift' : IDL.Bool,
    'groupMessage' : IDL.Bool,
    'roseReceipt' : IDL.Bool,
    'tradeRequest' : IDL.Bool,
    'systemNotice' : IDL.Bool,
    'storyView' : IDL.Bool,
    'like' : IDL.Bool,
    'comment' : IDL.Bool,
    'groupAdd' : IDL.Bool,
    'message' : IDL.Bool,
    'roseGift' : IDL.Bool,
    'follow' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'country' : IDL.Text,
    'username' : IDL.Text,
    'birthYear' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'emailPreferences' : IDL.Opt(EmailPreferences),
    'gender' : IDL.Opt(IDL.Text),
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const GroupMessage = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'content' : MessageType,
    'senderProfile' : IDL.Opt(UserProfile),
    'sender' : IDL.Principal,
    'groupId' : IDL.Nat,
    'isEdited' : IDL.Bool,
    'timestamp' : Time,
    'replyToId' : IDL.Opt(IDL.Nat),
    'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Principal))),
    'readBy' : IDL.Vec(IDL.Principal),
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'content' : MessageType,
    'senderProfile' : IDL.Opt(UserProfile),
    'sender' : IDL.Principal,
    'isEdited' : IDL.Bool,
    'timestamp' : Time,
    'replyToId' : IDL.Opt(IDL.Nat),
    'receiver' : IDL.Principal,
    'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Principal))),
    'readBy' : IDL.Vec(IDL.Principal),
  });
  const ProfileFilter = IDL.Record({
    'country' : IDL.Opt(IDL.Text),
    'minAge' : IDL.Opt(IDL.Nat),
    'gender' : IDL.Opt(IDL.Text),
    'maxAge' : IDL.Opt(IDL.Nat),
    'minBalance' : IDL.Opt(IDL.Float64),
  });
  const ProfileWithPrincipal = IDL.Record({
    'principal' : IDL.Principal,
    'balance' : IDL.Float64,
    'profile' : UserProfile,
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'content' : MessageType,
    'expiresAt' : Time,
    'author' : IDL.Principal,
    'viewCount' : IDL.Nat,
    'viewedBy' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
    'caption' : IDL.Opt(IDL.Text),
    'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Principal))),
  });
  const BlockRecord = IDL.Record({
    'blocked' : IDL.Principal,
    'blocker' : IDL.Principal,
    'timestamp' : Time,
  });
  const RoseTransactionType = IDL.Variant({
    'buy' : IDL.Null,
    'fee' : IDL.Null,
    'gift' : IDL.Null,
    'mint' : IDL.Null,
    'sell' : IDL.Null,
    'transfer' : IDL.Null,
  });
  const RoseTransaction = IDL.Record({
    'id' : IDL.Nat,
    'feeDistributed' : IDL.Float64,
    'transactionType' : RoseTransactionType,
    'sender' : IDL.Opt(IDL.Principal),
    'timestamp' : Time,
    'amount' : IDL.Float64,
    'receiver' : IDL.Opt(IDL.Principal),
  });
  const AnalyticsSummary = IDL.Record({
    'activeUsers' : IDL.Nat,
    'totalPlatformFees' : IDL.Float64,
    'totalRosesCirculating' : IDL.Float64,
    'totalRoseTransactions' : IDL.Nat,
    'totalMessages' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRoseGifts' : IDL.Float64,
    'totalPosts' : IDL.Nat,
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'embed' : IDL.Opt(IDL.Text),
    'author' : IDL.Principal,
    'viewCount' : IDL.Nat,
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
  });
  const UserAnalytics = IDL.Record({
    'giftsReceived' : IDL.Nat,
    'postCount' : IDL.Nat,
    'roseBalance' : IDL.Float64,
    'reactionsReceived' : IDL.Nat,
    'messageCount' : IDL.Nat,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'participants' : IDL.Vec(IDL.Principal),
    'messages' : IDL.Vec(Message),
    'otherParticipantProfile' : IDL.Opt(UserProfile),
  });
  const GroupChat = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'participants' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : Time,
    'admins' : IDL.Vec(IDL.Principal),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const NotificationCount = IDL.Record({
    'groupAddCount' : IDL.Nat,
    'storyViewCount' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'roseGiftCount' : IDL.Nat,
    'systemCount' : IDL.Nat,
    'totalCount' : IDL.Nat,
    'followCount' : IDL.Nat,
    'unreadCount' : IDL.Nat,
    'messageCount' : IDL.Nat,
    'roseReceiptCount' : IDL.Nat,
    'commentCount' : IDL.Nat,
    'tradeRequestCount' : IDL.Nat,
    'postGiftCount' : IDL.Nat,
    'groupMessageCount' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'postGift' : IDL.Null,
    'groupMessage' : IDL.Null,
    'roseReceipt' : IDL.Null,
    'tradeRequest' : IDL.Null,
    'systemNotice' : IDL.Null,
    'storyView' : IDL.Null,
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'groupAdd' : IDL.Null,
    'message' : IDL.Null,
    'roseGift' : IDL.Null,
    'follow' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'linkedId' : IDL.Opt(IDL.Text),
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'notificationType' : NotificationType,
    'isRead' : IDL.Bool,
    'timestamp' : Time,
    'linkedType' : IDL.Opt(IDL.Text),
  });
  const PlatformStats = IDL.Record({
    'totalMessages' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalInteractions' : IDL.Nat,
    'totalPosts' : IDL.Nat,
  });
  const CommentInteraction = IDL.Record({
    'id' : IDL.Nat,
    'parentCommentId' : IDL.Opt(IDL.Nat),
    'user' : IDL.Principal,
    'comment' : IDL.Text,
    'timestamp' : Time,
    'postId' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const GroupUnreadCount = IDL.Record({
    'groupId' : IDL.Nat,
    'unreadCount' : IDL.Nat,
  });
  const DirectUnreadCount = IDL.Record({
    'conversationId' : IDL.Nat,
    'unreadCount' : IDL.Nat,
  });
  const UnreadCounts = IDL.Record({
    'groups' : IDL.Vec(GroupUnreadCount),
    'direct' : IDL.Vec(DirectUnreadCount),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const SearchResult = IDL.Variant({
    'postResult' : IDL.Record({
      'author' : IDL.Principal,
      'searchType' : IDL.Text,
      'timestamp' : Time,
      'image' : IDL.Opt(ExternalBlob),
      'contentSnippet' : IDL.Text,
      'postId' : IDL.Text,
    }),
    'messageResult' : IDL.Record({
      'messageId' : IDL.Nat,
      'senderProfile' : IDL.Opt(UserProfile),
      'sender' : IDL.Principal,
      'searchType' : IDL.Text,
      'conversationId' : IDL.Nat,
      'timestamp' : Time,
      'contentSnippet' : IDL.Text,
      'receiver' : IDL.Principal,
    }),
    'userResult' : IDL.Record({
      'principal' : IDL.Principal,
      'balance' : IDL.Float64,
      'searchType' : IDL.Text,
      'profile' : UserProfile,
    }),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addGroupParticipant' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'buyRosesFromUser' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
    'claimAllRoses' : IDL.Func([], [], []),
    'cleanupExpiredStories' : IDL.Func([], [IDL.Nat], []),
    'clearAllNotifications' : IDL.Func([], [], []),
    'commentOnPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)], [], []),
    'convertBalanceToUsd' : IDL.Func([IDL.Float64], [IDL.Float64], []),
    'convertBalanceToUsdQuery' : IDL.Func(
        [IDL.Float64],
        [IDL.Float64],
        ['query'],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createGroupChat' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Principal), IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'createStory' : IDL.Func([MessageType, IDL.Opt(IDL.Text)], [IDL.Nat], []),
    'deleteCallerProfile' : IDL.Func([], [], []),
    'deleteComment' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteGroupMessage' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteMessage' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteNotification' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'editGroupMessage' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : GroupMessage, 'err' : IDL.Text })],
        [],
      ),
    'editMessage' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
        [],
      ),
    'editPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'filterProfiles' : IDL.Func(
        [ProfileFilter],
        [IDL.Vec(ProfileWithPrincipal)],
        ['query'],
      ),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'forwardGroupMessageToConversation' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
        [],
      ),
    'forwardMessage' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
        [],
      ),
    'forwardMessageToGroup' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : GroupMessage, 'err' : IDL.Text })],
        [],
      ),
    'forwardPostToConversation' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getAllBlockRecords' : IDL.Func([], [IDL.Vec(BlockRecord)], ['query']),
    'getAllRoseTransactions' : IDL.Func(
        [],
        [IDL.Vec(RoseTransaction)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerEmailPreferences' : IDL.Func(
        [],
        [
          IDL.Record({
            'email' : IDL.Opt(IDL.Text),
            'preferences' : IDL.Opt(EmailPreferences),
          }),
        ],
        ['query'],
      ),
    'getCallerPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserAnalytics' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : UserAnalytics, 'err' : IDL.Text })],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getGroupChats' : IDL.Func([], [IDL.Vec(GroupChat)], ['query']),
    'getGroupDetails' : IDL.Func([IDL.Nat], [GroupChat], ['query']),
    'getGroupMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(GroupMessage)],
        ['query'],
      ),
    'getGroupTypingUsers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getIcpUsdExchangeRate' : IDL.Func([], [IDL.Float64], []),
    'getNotificationCountByType' : IDL.Func([], [NotificationCount], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'notifications' : IDL.Vec(Notification),
          }),
        ],
        ['query'],
      ),
    'getOnlineUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getPinnedConversationMessage' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Message)],
        ['query'],
      ),
    'getPinnedGroupMessage' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(GroupMessage)],
        ['query'],
      ),
    'getPinnedStories' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
    'getPinnedTrendingPost' : IDL.Func([], [IDL.Opt(Post)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getPostComments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CommentInteraction)],
        ['query'],
      ),
    'getPostInteractions' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalRosesGifted' : IDL.Float64,
            'forwards' : IDL.Nat,
            'likes' : IDL.Nat,
            'saves' : IDL.Nat,
            'comments' : IDL.Nat,
            'roseGifts' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getPostViewCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPostsFromFollowedUsers' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getRoseBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getRoseSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalCirculating' : IDL.Float64,
            'feeRewards' : IDL.Float64,
            'userBalance' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getRoseTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(RoseTransaction)],
        ['query'],
      ),
    'getSavedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getStoryReactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Principal)))],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTotalCirculatingRoses' : IDL.Func([], [IDL.Float64], ['query']),
    'getTypingUsers' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
    'getUnreadCounts' : IDL.Func([], [UnreadCounts], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Record({ 'profileId' : IDL.Principal })],
        [UserProfile],
        ['query'],
      ),
    'getUserRoseBalance' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
    'getUserStories' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
    'giftRoses' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
    'giftRosesOnPost' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'giftRosesOnStory' : IDL.Func(
        [IDL.Nat, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isOnline' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'leaveConversation' : IDL.Func([IDL.Nat], [], []),
    'leaveGroup' : IDL.Func([IDL.Nat], [], []),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'markAllNotificationsAsRead' : IDL.Func([], [], []),
    'markConversationRead' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markGroupChatRead' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markGroupMessageRead' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markMessageRead' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'markStoryAsViewed' : IDL.Func([IDL.Nat], [], []),
    'pinConversationMessage' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'pinGroupMessage' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'pinPostToTrending' : IDL.Func([IDL.Text], [], []),
    'pinStory' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'reactToGroupMessage' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'reactToMessage' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'reactToStory' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'recordPostView' : IDL.Func([IDL.Text], [], []),
    'removeGroupParticipant' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'requestBuyRoses' : IDL.Func([IDL.Float64], [IDL.Text], []),
    'requestSellRoses' : IDL.Func([IDL.Float64], [IDL.Text], []),
    'saveCallerEmailPreferences' : IDL.Func(
        [IDL.Opt(IDL.Text), EmailPreferences],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePost' : IDL.Func([IDL.Text], [], []),
    'sellRosesToUser' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
    'sendGroupMessage' : IDL.Func(
        [IDL.Nat, MessageType, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Principal, MessageType, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'setGroupTyping' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setTyping' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'universalSearch' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Vec(SearchResult)],
        ['query'],
      ),
    'unlikePost' : IDL.Func([IDL.Text], [], []),
    'unpinConversationMessage' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unpinGroupMessage' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unpinStory' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unpinTrendingPost' : IDL.Func([], [], []),
    'unreactToStory' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unsavePost' : IDL.Func([IDL.Text], [], []),
    'updateGroupAvatar' : IDL.Func([IDL.Nat, IDL.Opt(ExternalBlob)], [], []),
    'updateGroupName' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateLastActive' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };