/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'activeUsers' : bigint,
  'totalPlatformFees' : number,
  'totalRosesCirculating' : number,
  'totalRoseTransactions' : bigint,
  'totalMessages' : bigint,
  'totalUsers' : bigint,
  'totalRoseGifts' : number,
  'totalPosts' : bigint,
}
export interface BlockRecord {
  'blocked' : Principal,
  'blocker' : Principal,
  'timestamp' : Time,
}
export interface CommentInteraction {
  'id' : bigint,
  'parentCommentId' : [] | [bigint],
  'user' : Principal,
  'comment' : string,
  'timestamp' : Time,
  'postId' : string,
}
export interface Conversation {
  'id' : bigint,
  'participants' : Array<Principal>,
  'messages' : Array<Message>,
  'otherParticipantProfile' : [] | [UserProfile],
}
export interface DirectUnreadCount {
  'conversationId' : bigint,
  'unreadCount' : bigint,
}
export interface EmailPreferences {
  'postGift' : boolean,
  'groupMessage' : boolean,
  'roseReceipt' : boolean,
  'tradeRequest' : boolean,
  'systemNotice' : boolean,
  'storyReaction' : boolean,
  'storyView' : boolean,
  'like' : boolean,
  'comment' : boolean,
  'groupAdd' : boolean,
  'message' : boolean,
  'roseGift' : boolean,
  'follow' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface GroupChat {
  'id' : bigint,
  'creator' : Principal,
  'participants' : Array<Principal>,
  'name' : string,
  'createdAt' : Time,
  'admins' : Array<Principal>,
  'avatar' : [] | [ExternalBlob],
}
export interface GroupMessage {
  'id' : bigint,
  'isDeleted' : boolean,
  'content' : MessageType,
  'senderProfile' : [] | [UserProfile],
  'sender' : Principal,
  'groupId' : bigint,
  'isEdited' : boolean,
  'timestamp' : Time,
  'replyToId' : [] | [bigint],
  'reactions' : Array<[string, Array<Principal>]>,
  'readBy' : Array<Principal>,
}
export interface GroupUnreadCount { 'groupId' : bigint, 'unreadCount' : bigint }
export interface Message {
  'id' : bigint,
  'isDeleted' : boolean,
  'content' : MessageType,
  'senderProfile' : [] | [UserProfile],
  'sender' : Principal,
  'isEdited' : boolean,
  'timestamp' : Time,
  'replyToId' : [] | [bigint],
  'receiver' : Principal,
  'reactions' : Array<[string, Array<Principal>]>,
  'readBy' : Array<Principal>,
}
export type MessageType = { 'media' : ExternalBlob } |
  { 'tradeRequest' : TradeRequestMessage } |
  { 'receipt' : ReceiptMessage } |
  { 'video' : ExternalBlob } |
  { 'voice' : ExternalBlob } |
  { 'rose' : number } |
  { 'text' : string } |
  { 'image' : ExternalBlob } |
  {
    'forwardedPost' : {
      'author' : Principal,
      'timestamp' : Time,
      'image' : [] | [ExternalBlob],
      'contentSnippet' : string,
      'postId' : string,
    }
  };
export interface Notification {
  'id' : bigint,
  'linkedId' : [] | [string],
  'content' : string,
  'userId' : Principal,
  'notificationType' : NotificationType,
  'isRead' : boolean,
  'timestamp' : Time,
  'linkedType' : [] | [string],
}
export interface NotificationCount {
  'groupAddCount' : bigint,
  'storyViewCount' : bigint,
  'likeCount' : bigint,
  'roseGiftCount' : bigint,
  'systemCount' : bigint,
  'totalCount' : bigint,
  'followCount' : bigint,
  'unreadCount' : bigint,
  'messageCount' : bigint,
  'roseReceiptCount' : bigint,
  'commentCount' : bigint,
  'storyReactionCount' : bigint,
  'tradeRequestCount' : bigint,
  'postGiftCount' : bigint,
  'groupMessageCount' : bigint,
}
export type NotificationType = { 'postGift' : null } |
  { 'groupMessage' : null } |
  { 'roseReceipt' : null } |
  { 'tradeRequest' : null } |
  { 'systemNotice' : null } |
  { 'storyReaction' : null } |
  { 'storyView' : null } |
  { 'like' : null } |
  { 'comment' : null } |
  { 'groupAdd' : null } |
  { 'message' : null } |
  { 'roseGift' : null } |
  { 'follow' : null };
export interface PlatformStats {
  'totalMessages' : bigint,
  'totalUsers' : bigint,
  'totalInteractions' : bigint,
  'totalPosts' : bigint,
}
export interface Post {
  'id' : string,
  'content' : string,
  'embed' : [] | [string],
  'author' : Principal,
  'viewCount' : bigint,
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
}
export interface ProfileFilter {
  'country' : [] | [string],
  'minAge' : [] | [bigint],
  'onlineOnly' : [] | [boolean],
  'gender' : [] | [string],
  'maxAge' : [] | [bigint],
  'minBalance' : [] | [number],
}
export interface ProfileWithPrincipal {
  'principal' : Principal,
  'balance' : number,
  'profile' : UserProfile,
}
export interface ReceiptMessage {
  'fee' : number,
  'sender' : Principal,
  'summary' : string,
  'timestamp' : Time,
  'amount' : number,
  'receiver' : Principal,
}
export interface RoseTransaction {
  'id' : bigint,
  'feeDistributed' : number,
  'transactionType' : RoseTransactionType,
  'sender' : [] | [Principal],
  'timestamp' : Time,
  'amount' : number,
  'receiver' : [] | [Principal],
}
export type RoseTransactionType = { 'buy' : null } |
  { 'fee' : null } |
  { 'charityClaim' : null } |
  { 'gift' : null } |
  { 'mint' : null } |
  { 'sell' : null } |
  { 'charityDonate' : null } |
  { 'transfer' : null };
export type SearchResult = {
    'postResult' : {
      'author' : Principal,
      'searchType' : string,
      'timestamp' : Time,
      'image' : [] | [ExternalBlob],
      'contentSnippet' : string,
      'postId' : string,
    }
  } |
  {
    'messageResult' : {
      'messageId' : bigint,
      'senderProfile' : [] | [UserProfile],
      'sender' : Principal,
      'searchType' : string,
      'conversationId' : bigint,
      'timestamp' : Time,
      'contentSnippet' : string,
      'receiver' : Principal,
    }
  } |
  {
    'userResult' : {
      'principal' : Principal,
      'balance' : number,
      'searchType' : string,
      'profile' : UserProfile,
    }
  };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface Story {
  'id' : bigint,
  'content' : MessageType,
  'expiresAt' : Time,
  'author' : Principal,
  'viewCount' : bigint,
  'viewedBy' : Array<Principal>,
  'timestamp' : Time,
  'caption' : [] | [string],
  'reactions' : Array<[string, Array<Principal>]>,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TradeRequestMessage {
  'requester' : Principal,
  'summary' : string,
  'timestamp' : Time,
  'amount' : number,
  'requestType' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UnreadCounts {
  'groups' : Array<GroupUnreadCount>,
  'direct' : Array<DirectUnreadCount>,
}
export interface UserAnalytics {
  'giftsReceived' : bigint,
  'postCount' : bigint,
  'roseBalance' : number,
  'reactionsReceived' : bigint,
  'messageCount' : bigint,
}
export interface UserProfile {
  'bio' : [] | [string],
  'country' : string,
  'username' : string,
  'birthYear' : [] | [bigint],
  'name' : string,
  'email' : [] | [string],
  'emailPreferences' : [] | [EmailPreferences],
  'gender' : [] | [string],
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addGroupParticipant' : ActorMethod<[bigint, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'buyRosesFromUser' : ActorMethod<[Principal, number], undefined>,
  'claimAllRoses' : ActorMethod<[], undefined>,
  /**
   * / Claim 0.01 Rose from the charity pool once every 24 hours.
   * / The 5% fee is applied: caller receives 0.01 * 0.95 = 0.0095 Roses after fee.
   */
  'claimDailyCharity' : ActorMethod<[], string>,
  'cleanupExpiredStories' : ActorMethod<[], bigint>,
  'clearAllNotifications' : ActorMethod<[], undefined>,
  'commentOnPost' : ActorMethod<[string, string, [] | [bigint]], undefined>,
  'convertBalanceToUsd' : ActorMethod<[number], number>,
  'convertBalanceToUsdQuery' : ActorMethod<[number], number>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGroupChat' : ActorMethod<
    [string, Array<Principal>, [] | [ExternalBlob]],
    bigint
  >,
  'createPost' : ActorMethod<
    [string, [] | [ExternalBlob], [] | [string]],
    undefined
  >,
  'createStory' : ActorMethod<[MessageType, [] | [string]], bigint>,
  'deleteCallerProfile' : ActorMethod<[], undefined>,
  'deleteComment' : ActorMethod<[string, bigint], undefined>,
  'deleteGroupMessage' : ActorMethod<
    [bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteMessage' : ActorMethod<
    [bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteNotification' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  /**
   * / Donate `amount` Roses to the charity pool.
   * / The standard 5% platform fee is applied: fee is distributed pro-rata to
   * / all holders, and the net (amount * 0.95) goes into charityPool.
   */
  'donateToCharity' : ActorMethod<[number], string>,
  'editGroupMessage' : ActorMethod<
    [bigint, bigint, string],
    { 'ok' : GroupMessage } |
      { 'err' : string }
  >,
  'editMessage' : ActorMethod<
    [bigint, bigint, string],
    { 'ok' : Message } |
      { 'err' : string }
  >,
  'editPost' : ActorMethod<
    [string, string, [] | [ExternalBlob], [] | [string]],
    undefined
  >,
  'filterProfiles' : ActorMethod<
    [ProfileFilter, bigint, bigint],
    Array<ProfileWithPrincipal>
  >,
  'followUser' : ActorMethod<[Principal], undefined>,
  'forwardGroupMessageToConversation' : ActorMethod<
    [bigint, bigint, bigint],
    { 'ok' : Message } |
      { 'err' : string }
  >,
  'forwardMessage' : ActorMethod<
    [bigint, bigint, bigint],
    { 'ok' : Message } |
      { 'err' : string }
  >,
  'forwardMessageToGroup' : ActorMethod<
    [bigint, bigint, bigint],
    { 'ok' : GroupMessage } |
      { 'err' : string }
  >,
  'forwardPostToConversation' : ActorMethod<[string, bigint], undefined>,
  'getActiveStories' : ActorMethod<[], Array<Story>>,
  'getAllBlockRecords' : ActorMethod<[], Array<BlockRecord>>,
  'getAllRoseTransactions' : ActorMethod<[], Array<RoseTransaction>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getBlockedUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerEmailPreferences' : ActorMethod<
    [],
    { 'email' : [] | [string], 'preferences' : [] | [EmailPreferences] }
  >,
  'getCallerPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getCallerUserAnalytics' : ActorMethod<
    [],
    { 'ok' : UserAnalytics } |
      { 'err' : string }
  >,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Returns the current charity pool balance and the caller's last claim timestamp.
   */
  'getCharityInfo' : ActorMethod<
    [],
    { 'pool' : number, 'lastClaimTime' : [] | [bigint] }
  >,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getFollowerCount' : ActorMethod<[Principal], bigint>,
  'getFollowingCount' : ActorMethod<[Principal], bigint>,
  'getGroupChats' : ActorMethod<[], Array<GroupChat>>,
  'getGroupDetails' : ActorMethod<[bigint], GroupChat>,
  'getGroupMessages' : ActorMethod<[bigint], Array<GroupMessage>>,
  'getGroupTypingUsers' : ActorMethod<[bigint], Array<Principal>>,
  'getIcpUsdExchangeRate' : ActorMethod<[], number>,
  'getLastSeen' : ActorMethod<[Principal], [] | [bigint]>,
  'getNotificationCountByType' : ActorMethod<[], NotificationCount>,
  'getNotifications' : ActorMethod<
    [bigint, bigint],
    { 'total' : bigint, 'notifications' : Array<Notification> }
  >,
  'getOnlineUsers' : ActorMethod<[], Array<Principal>>,
  /**
   * / Returns the pinned message for a direct conversation, or null if none is pinned.
   */
  'getPinnedConversationMessage' : ActorMethod<[Principal], [] | [Message]>,
  /**
   * / Returns the pinned group message, or null if none is pinned.
   */
  'getPinnedGroupMessage' : ActorMethod<[bigint], [] | [GroupMessage]>,
  'getPinnedStories' : ActorMethod<[Principal], Array<Story>>,
  'getPinnedTrendingPost' : ActorMethod<[], [] | [Post]>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getPostComments' : ActorMethod<[string], Array<CommentInteraction>>,
  'getPostCountByUser' : ActorMethod<[Principal], bigint>,
  'getPostInteractions' : ActorMethod<
    [string],
    {
      'totalRosesGifted' : number,
      'forwards' : bigint,
      'likes' : bigint,
      'saves' : bigint,
      'comments' : bigint,
      'roseGifts' : bigint,
    }
  >,
  'getPostViewCount' : ActorMethod<[string], bigint>,
  'getPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getPostsFromFollowedUsers' : ActorMethod<[], Array<Post>>,
  'getRoseBalance' : ActorMethod<[], number>,
  'getRoseSummary' : ActorMethod<
    [],
    {
      'totalCirculating' : number,
      'feeRewards' : number,
      'userBalance' : number,
    }
  >,
  'getRoseTransactionHistory' : ActorMethod<[], Array<RoseTransaction>>,
  'getSavedPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getStoryReactions' : ActorMethod<
    [bigint],
    Array<[string, Array<Principal>]>
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTotalCirculatingRoses' : ActorMethod<[], number>,
  'getTypingUsers' : ActorMethod<[bigint], Array<Principal>>,
  'getUnreadCounts' : ActorMethod<[], UnreadCounts>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserByUsername' : ActorMethod<[string], [] | [Principal]>,
  'getUserPosts' : ActorMethod<[Principal, bigint, bigint], Array<Post>>,
  'getUserProfile' : ActorMethod<[{ 'profileId' : Principal }], UserProfile>,
  'getUserRoseBalance' : ActorMethod<[Principal], number>,
  'getUserStories' : ActorMethod<[Principal], Array<Story>>,
  'giftRoses' : ActorMethod<[Principal, number], undefined>,
  'giftRosesOnPost' : ActorMethod<[string, number], undefined>,
  'giftRosesOnStory' : ActorMethod<
    [bigint, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'isOnline' : ActorMethod<[Principal], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isUserBlocked' : ActorMethod<[Principal], boolean>,
  'leaveConversation' : ActorMethod<[bigint], undefined>,
  'leaveGroup' : ActorMethod<[bigint], undefined>,
  'likePost' : ActorMethod<[string], undefined>,
  'markAllNotificationsAsRead' : ActorMethod<[], undefined>,
  'markConversationRead' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markGroupChatRead' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markGroupMessageRead' : ActorMethod<
    [bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markMessageRead' : ActorMethod<
    [Principal, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'markStoryAsViewed' : ActorMethod<[bigint], undefined>,
  /**
   * / Pin a message in a direct conversation. Any participant can pin.
   * / Replaces any previously pinned message.
   */
  'pinConversationMessage' : ActorMethod<
    [Principal, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Pin a message in a group chat. Only group creator or admins can pin.
   * / Replaces any previously pinned message.
   */
  'pinGroupMessage' : ActorMethod<
    [bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'pinPostToTrending' : ActorMethod<[string], undefined>,
  'pinStory' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'reactToGroupMessage' : ActorMethod<
    [bigint, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'reactToMessage' : ActorMethod<
    [Principal, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'reactToStory' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'recordPostView' : ActorMethod<[string], undefined>,
  'removeGroupParticipant' : ActorMethod<[bigint, Principal], undefined>,
  'requestBuyRoses' : ActorMethod<[number], string>,
  'requestSellRoses' : ActorMethod<[number], string>,
  'saveCallerEmailPreferences' : ActorMethod<
    [[] | [string], EmailPreferences],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePost' : ActorMethod<[string], undefined>,
  'sellRosesToUser' : ActorMethod<[Principal, number], undefined>,
  'sendGroupMessage' : ActorMethod<
    [bigint, MessageType, [] | [bigint]],
    undefined
  >,
  'sendMessage' : ActorMethod<
    [Principal, MessageType, [] | [bigint]],
    undefined
  >,
  'setGroupTyping' : ActorMethod<[bigint, boolean], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setTyping' : ActorMethod<[bigint, boolean], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'universalSearch' : ActorMethod<[string, [] | [bigint]], Array<SearchResult>>,
  'unlikePost' : ActorMethod<[string], undefined>,
  /**
   * / Unpin the currently pinned message in a direct conversation. Any participant can unpin.
   */
  'unpinConversationMessage' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Unpin the currently pinned message in a group chat. Only group creator or admins can unpin.
   */
  'unpinGroupMessage' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'unpinStory' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'unpinTrendingPost' : ActorMethod<[], undefined>,
  'unreactToStory' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'unsavePost' : ActorMethod<[string], undefined>,
  'updateGroupAvatar' : ActorMethod<[bigint, [] | [ExternalBlob]], undefined>,
  'updateGroupName' : ActorMethod<[bigint, string], undefined>,
  'updateLastActive' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];