/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'activeUsers' : bigint,
  'totalPlatformFees' : number,
  'totalRosesCirculating' : number,
  'totalRoseTransactions' : bigint,
  'totalMessages' : bigint,
  'totalUsers' : bigint,
  'totalRoseGifts' : number,
  'totalPosts' : bigint,
}
export interface BlockRecord {
  'blocked' : Principal,
  'blocker' : Principal,
  'timestamp' : Time,
}
export interface CommentInteraction {
  'id' : bigint,
  'parentCommentId' : [] | [bigint],
  'user' : Principal,
  'comment' : string,
  'timestamp' : Time,
  'postId' : string,
}
export interface Conversation {
  'id' : bigint,
  'participants' : Array<Principal>,
  'messages' : Array<Message>,
  'otherParticipantProfile' : [] | [UserProfile],
}
export type ExternalBlob = Uint8Array;
export interface GroupChat {
  'id' : bigint,
  'creator' : Principal,
  'participants' : Array<Principal>,
  'name' : string,
  'createdAt' : Time,
  'admins' : Array<Principal>,
  'avatar' : [] | [ExternalBlob],
}
export interface GroupMessage {
  'id' : bigint,
  'content' : MessageType,
  'senderProfile' : [] | [UserProfile],
  'sender' : Principal,
  'groupId' : bigint,
  'timestamp' : Time,
}
export interface Message {
  'id' : bigint,
  'content' : MessageType,
  'senderProfile' : [] | [UserProfile],
  'sender' : Principal,
  'timestamp' : Time,
  'receiver' : Principal,
}
export type MessageType = { 'media' : ExternalBlob } |
  { 'tradeRequest' : TradeRequestMessage } |
  { 'receipt' : ReceiptMessage } |
  { 'video' : ExternalBlob } |
  { 'voice' : ExternalBlob } |
  { 'rose' : number } |
  { 'text' : string } |
  { 'image' : ExternalBlob } |
  {
    'forwardedPost' : {
      'author' : Principal,
      'timestamp' : Time,
      'image' : [] | [ExternalBlob],
      'contentSnippet' : string,
      'postId' : string,
    }
  };
export interface Notification {
  'id' : bigint,
  'linkedId' : [] | [string],
  'content' : string,
  'userId' : Principal,
  'notificationType' : NotificationType,
  'isRead' : boolean,
  'timestamp' : Time,
  'linkedType' : [] | [string],
}
export interface NotificationCount {
  'groupAddCount' : bigint,
  'storyViewCount' : bigint,
  'likeCount' : bigint,
  'roseGiftCount' : bigint,
  'systemCount' : bigint,
  'totalCount' : bigint,
  'followCount' : bigint,
  'unreadCount' : bigint,
  'messageCount' : bigint,
  'roseReceiptCount' : bigint,
  'commentCount' : bigint,
  'tradeRequestCount' : bigint,
  'postGiftCount' : bigint,
  'groupMessageCount' : bigint,
}
export type NotificationType = { 'postGift' : null } |
  { 'groupMessage' : null } |
  { 'roseReceipt' : null } |
  { 'tradeRequest' : null } |
  { 'systemNotice' : null } |
  { 'storyView' : null } |
  { 'like' : null } |
  { 'comment' : null } |
  { 'groupAdd' : null } |
  { 'message' : null } |
  { 'roseGift' : null } |
  { 'follow' : null };
export interface Post {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
}
export interface ProfileFilter {
  'country' : [] | [string],
  'minAge' : [] | [bigint],
  'gender' : [] | [string],
  'maxAge' : [] | [bigint],
  'minBalance' : [] | [number],
}
export interface ProfileWithPrincipal {
  'principal' : Principal,
  'balance' : number,
  'profile' : UserProfile,
}
export interface ReceiptMessage {
  'fee' : number,
  'sender' : Principal,
  'summary' : string,
  'timestamp' : Time,
  'amount' : number,
  'receiver' : Principal,
}
export interface RoseTransaction {
  'id' : bigint,
  'feeDistributed' : number,
  'transactionType' : RoseTransactionType,
  'sender' : [] | [Principal],
  'timestamp' : Time,
  'amount' : number,
  'receiver' : [] | [Principal],
}
export type RoseTransactionType = { 'buy' : null } |
  { 'fee' : null } |
  { 'gift' : null } |
  { 'mint' : null } |
  { 'sell' : null } |
  { 'transfer' : null };
export type SearchResult = {
    'postResult' : {
      'author' : Principal,
      'searchType' : string,
      'timestamp' : Time,
      'image' : [] | [ExternalBlob],
      'contentSnippet' : string,
      'postId' : string,
    }
  } |
  {
    'messageResult' : {
      'messageId' : bigint,
      'senderProfile' : [] | [UserProfile],
      'sender' : Principal,
      'searchType' : string,
      'conversationId' : bigint,
      'timestamp' : Time,
      'contentSnippet' : string,
      'receiver' : Principal,
    }
  } |
  {
    'userResult' : {
      'principal' : Principal,
      'balance' : number,
      'searchType' : string,
      'profile' : UserProfile,
    }
  };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface Story {
  'id' : bigint,
  'content' : MessageType,
  'expiresAt' : Time,
  'author' : Principal,
  'viewedBy' : Array<Principal>,
  'timestamp' : Time,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TradeRequestMessage {
  'requester' : Principal,
  'summary' : string,
  'timestamp' : Time,
  'amount' : number,
  'requestType' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'bio' : [] | [string],
  'country' : string,
  'username' : string,
  'birthYear' : [] | [bigint],
  'name' : string,
  'gender' : [] | [string],
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addGroupParticipant' : ActorMethod<[bigint, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'buyRosesFromUser' : ActorMethod<[Principal, number], undefined>,
  'claimAllRoses' : ActorMethod<[], undefined>,
  'cleanupExpiredStories' : ActorMethod<[], bigint>,
  'clearAllNotifications' : ActorMethod<[], undefined>,
  'commentOnPost' : ActorMethod<[string, string, [] | [bigint]], undefined>,
  'convertBalanceToUsd' : ActorMethod<[number], number>,
  'convertBalanceToUsdQuery' : ActorMethod<[number], number>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGroupChat' : ActorMethod<
    [string, Array<Principal>, [] | [ExternalBlob]],
    bigint
  >,
  'createPost' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
  'createStory' : ActorMethod<[MessageType], bigint>,
  'deleteCallerProfile' : ActorMethod<[], undefined>,
  'deleteComment' : ActorMethod<[string, bigint], undefined>,
  'deleteMessage' : ActorMethod<[bigint, bigint], undefined>,
  'deleteNotification' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'editMessage' : ActorMethod<[bigint, bigint, MessageType], undefined>,
  'editPost' : ActorMethod<[string, string, [] | [ExternalBlob]], undefined>,
  'filterProfiles' : ActorMethod<[ProfileFilter], Array<ProfileWithPrincipal>>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'forwardPostToConversation' : ActorMethod<[string, bigint], undefined>,
  'getActiveStories' : ActorMethod<[], Array<Story>>,
  'getAllBlockRecords' : ActorMethod<[], Array<BlockRecord>>,
  'getAllRoseTransactions' : ActorMethod<[], Array<RoseTransaction>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getBlockedUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerPosts' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getFollowerCount' : ActorMethod<[Principal], bigint>,
  'getFollowingCount' : ActorMethod<[Principal], bigint>,
  'getGroupChats' : ActorMethod<[], Array<GroupChat>>,
  'getGroupDetails' : ActorMethod<[bigint], GroupChat>,
  'getGroupMessages' : ActorMethod<[bigint], Array<GroupMessage>>,
  'getIcpUsdExchangeRate' : ActorMethod<[], number>,
  'getNotificationCountByType' : ActorMethod<[], NotificationCount>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPinnedTrendingPost' : ActorMethod<[], [] | [Post]>,
  'getPostComments' : ActorMethod<[string], Array<CommentInteraction>>,
  'getPostInteractions' : ActorMethod<
    [string],
    {
      'totalRosesGifted' : number,
      'forwards' : bigint,
      'likes' : bigint,
      'saves' : bigint,
      'comments' : bigint,
      'roseGifts' : bigint,
    }
  >,
  'getPosts' : ActorMethod<[], Array<Post>>,
  'getPostsFromFollowedUsers' : ActorMethod<[], Array<Post>>,
  'getRoseBalance' : ActorMethod<[], number>,
  'getRoseSummary' : ActorMethod<
    [],
    {
      'totalCirculating' : number,
      'feeRewards' : number,
      'userBalance' : number,
    }
  >,
  'getRoseTransactionHistory' : ActorMethod<[], Array<RoseTransaction>>,
  'getSavedPosts' : ActorMethod<[], Array<Post>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTotalCirculatingRoses' : ActorMethod<[], number>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserPosts' : ActorMethod<[Principal], Array<Post>>,
  'getUserProfile' : ActorMethod<[{ 'profileId' : Principal }], UserProfile>,
  'getUserRoseBalance' : ActorMethod<[Principal], number>,
  'getUserStories' : ActorMethod<[Principal], Array<Story>>,
  'giftRoses' : ActorMethod<[Principal, number], undefined>,
  'giftRosesOnPost' : ActorMethod<[string, number], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isUserBlocked' : ActorMethod<[Principal], boolean>,
  'leaveConversation' : ActorMethod<[bigint], undefined>,
  'leaveGroup' : ActorMethod<[bigint], undefined>,
  'likePost' : ActorMethod<[string], undefined>,
  'markAllNotificationsAsRead' : ActorMethod<[], undefined>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'markStoryAsViewed' : ActorMethod<[bigint], undefined>,
  'pinPostToTrending' : ActorMethod<[string], undefined>,
  'removeGroupParticipant' : ActorMethod<[bigint, Principal], undefined>,
  'requestBuyRoses' : ActorMethod<[number], string>,
  'requestSellRoses' : ActorMethod<[number], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePost' : ActorMethod<[string], undefined>,
  'sellRosesToUser' : ActorMethod<[Principal, number], undefined>,
  'sendGroupMessage' : ActorMethod<[bigint, MessageType], undefined>,
  'sendMessage' : ActorMethod<[Principal, MessageType], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'universalSearch' : ActorMethod<[string, [] | [bigint]], Array<SearchResult>>,
  'unlikePost' : ActorMethod<[string], undefined>,
  'unpinTrendingPost' : ActorMethod<[], undefined>,
  'unsavePost' : ActorMethod<[string], undefined>,
  'updateGroupAvatar' : ActorMethod<[bigint, [] | [ExternalBlob]], undefined>,
  'updateGroupName' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];